# -*- coding: utf-8 -*-
"""Practical no. 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSn5Azyq7KORMXU41JXw9cxCd0XeTcCi
"""

import seaborn as sns
# Load the Titanic dataset
titanic = sns.load_dataset('titanic')
sns.set_style('whitegrid')
sns.barplot(x='sex', y='survived', data=titanic)

sns.set_style('whitegrid')
sns.barplot(x='class', y='survived', data=titanic)

sns.barplot(x='class', y='fare', data=titanic)

import seaborn as sns
import matplotlib.pyplot as plt
# Load the Titanic dataset
titanic = sns.load_dataset('titanic')
# Set the plotting style
sns.set_style('whitegrid')
# Plot the histogram of ticket prices
sns.histplot(x='fare', data=titanic, kde=True)
# Set the title and labels
plt.title('Ticket Price Distribution')
plt.xlabel('Ticket Fare')
plt.ylabel('Count')
# Display the plot
plt.show()