# -*- coding: utf-8 -*-
"""Practical no. 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSrQSFXntgppb2HLoCL6K1Pt3od21yGK
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Download the Iris dataset and load it into a DataFrame
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width','class']
iris_df = pd.read_csv(url, names=column_names)

feature_types = iris_df.dtypes
print("Features and their types:")
print(feature_types)

iris_df.hist(figsize=(6, 4))
plt.suptitle("Histograms of Iris Dataset Features")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
iris_df.boxplot()
plt.title("Box Plots of Iris Dataset Features")
plt.xticks(rotation=45)
plt.show()

# Compare distributions using violin plots
plt.figure(figsize=(6, 2))
sns.violinplot(data=iris_df)
plt.title("Violin Plots of Iris Dataset Features")
plt.xticks(rotation=45)
plt.show()

# Identify outliers using box plots
plt.figure(figsize=(4, 2))
sns.boxplot(data=iris_df)
plt.title("Box Plots of Iris Dataset Features (Outliers)")
plt.xticks(rotation=45)
plt.show()